#!/bin/bash
# Copyright (c) 2013 Joyent Inc. All rights reserved.
#
# A prepare-image script for `imgadm create -s prepare-image-script ...`
# for a Linux guest of a SmartOS hypervisor. See the "PREPARE IMAGE SCRIPTS"
# section of `man imgadm` and Joyent's OS-2550 for details.
#
# Intended supported distros: CentOS (not yet tested), Debian (not yet tested),
# and Ubuntu.
#

set -o errexit
set -o pipefail

# Trace logging to /tmp/prepare-image-trace.log to be partially passed back
# as prepare-image:error. Note that I would have used 'prepare-image:trace'
# but deployed `imgadm` is already looking for the former.
TRACELOG=/tmp/prepare-image-trace.log
touch $TRACELOG
exec 4<> $TRACELOG
export PS4='[\D{%FT%TZ}] :${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
export BASH_XTRACEFD=4
set -o xtrace

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games


#---- error handling

trap 'errexit $?' EXIT

function fatal
{
    echo "linux-prepare-image: fatal error: $*"
    exit 1
}

function errexit
{
    set +o xtrace
    set +o errexit
    set +o pipefail
    if [[ $1 -eq 0 ]]; then
        exit 0
    fi
    echo "error exit status $1"
    cat $TRACELOG | tail -n50 | /usr/sbin/mdata-put prepare-image:error
    /usr/sbin/mdata-put prepare-image:state error
    fatal "error exit status $1"
}


#---- support routines

function cleanup_logs() {
    find /var/log -type f | xargs rm -f
    # Create wtmp - this solves an issue where syslog would not start.
    touch /var/log/wtmp
    chmod 664 /var/log/wtmp
}


function cleanup_root() {
    # Cleaning up root account
    rm -f /root/.bash_history
    history -c
    history -w || true
    rm -f /root/.bash_history
    history -c
    history -w || true
    rm -f /root/.bash_history
    rm -f /root/.lesshst
    rm -f /root/.viminfo

    # Removing password for root
    passwd -d root
}

function cleanup_ssh() {
    find /etc/ssh -type f -name "ssh_host_*" | xargs rm -f
    FILELIST='authorized_keys known_hosts id_dsa id_dsa.pub id_rsa id_rsa.pub ssh_config'
    for FILE in $FILELIST; do
        if [ -f "/root/.ssh/$FILE" ]; then
            rm -r /root/.ssh/$FILE
        fi
    done
}

function cleanup_disks() {
    echo "removing /dev/vdb entries from fstab"
    sed -i '/^\/dev\/vdb/d' /etc/fstab
}

function cleanup_metadata() {
    # These files are in the centos 2.6.0 image. Not in the ubuntu or
    # ubuntu-certified images.
    rm -f /var/run/smartdc/user-script
    rm -f /var/lock/smartdc/user-script.lock
}

function cleanup_hostname() {
    rm -f /etc/hostname
    touch /etc/hostname
}

function prepare_centos() {
    # Cleaning up network devices.

    if [[ -f /etc/udev/rules.d/70-persistent-net.rules ]] ; then
        rm -f /etc/udev/rules.d/70-persistent-net.rules
    fi

    find /etc/sysconfig/network-scripts -name "ifcfg-eth*" | xargs rm -f

    if [[ -d /var/lib/dhcp3 ]] ; then
        find /var/lib/dhcp3 -type f -name "*.leases" | xargs rm -f
    elif [[ -d /var/lib/dhcp ]] ; then
        find /var/lib/dhcp -type f -name "*.leases" | xargs rm -f
    elif [[ -d /var/lib/dhclient ]] ; then
        find /var/lib/dhclient -type f | xargs rm -f
    fi

    # Create a eth0, eth1 and loopback by default
    if [[ -d /etc/sysconfig/network-scripts ]] ; then
        echo "# Created by Joyent linux-prepare-image" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        echo "DEVICE=\"eth0\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        echo "ONBOOT=\"yes\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        echo "BOOTPROTO=\"dhcp\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0

        echo "# Created by Joyent linux-prepare-image" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        echo "DEVICE=\"eth1\"" >>  /etc/sysconfig/network-scripts/ifcfg-eth1
        echo "ONBOOT=\"yes\"" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        echo "BOOTPROTO=\"dhcp\"" >> /etc/sysconfig/network-scripts/ifcfg-eth1

        echo "# Created by Joyent linux-prepare-image" > /etc/sysconfig/network-scripts/ifcfg-lo
        echo "DEVICE=lo" >> /etc/sysconfig/network-scripts/ifcfg-lo
        echo "IPADDR=127.0.0.1" >> /etc/sysconfig/network-scripts/ifcfg-lo
        echo "NETMASK=255.0.0.0" >> /etc/sysconfig/network-scripts/ifcfg-lo
        echo "NETWORK=127.0.0.0" >> /etc/sysconfig/network-scripts/ifcfg-lo
        echo "BROADCAST=127.255.255.255" >> /etc/sysconfig/network-scripts/ifcfg-lo
        echo "ONBOOT=yes" >> /etc/sysconfig/network-scripts/ifcfg-lo
        echo "NAME=loopback" >> /etc/sysconfig/network-scripts/ifcfg-lo
    fi

    # Cleaning up package cache.
    yum clean all 2>&1 >/dev/null

    # Make sure locale is set to prevent error when system is SSH'ed into.
    localedef --no-archive -i en_US -f UTF-8 en_US.UTF-8
}

function prepare_ubuntu() {
    # Cleaning up network devices.
    if [[ -f /etc/udev/rules.d/70-persistent-net.rules ]] ; then
        rm -f /etc/udev/rules.d/70-persistent-net.rules
    fi

    if [[ -d /var/lib/dhcp3 ]] ; then
        find /var/lib/dhcp3 -type f -name "*.leases" | xargs rm -f
    elif [[ -d /var/lib/dhcp ]] ; then
        find /var/lib/dhcp -type f -name "*.leases" | xargs rm -f
    fi

    # Use DHCP.
    # These are already configured in ubuntu-certified (presumably by
    # cloud-init) in /etc/network/interfaces.d/eth{0,1}.cfg. Skip there.
    if [[ -f /etc/network/interfaces && ! -d /etc/network/interfaces.d ]]; then
        rm -f /etc/network/interfaces
        out=$(dpkg-reconfigure ifupdown 2>&1 > /dev/null)
        echo "" >> /etc/network/interfaces
        echo "auto eth0" >> /etc/network/interfaces
        echo "iface eth0 inet dhcp" >> /etc/network/interfaces
        echo "auto eth1" >> /etc/network/interfaces
        echo "iface eth1 inet dhcp" >> /etc/network/interfaces
    fi
}

# Makes sure that /lib/smartdc et al are sane.
function prepare_lib_smartdc() {
    local DISTRO=$1

    # Per IMAGE-446 we need to remove the firstboot guard file for a new image.
    rm -f /lib/smartdc/.firstboot-complete-do-not-delete

    # Note: Not sure this is currently necessary.
    chown -R root:root /lib/smartdc
}



#---- mainline

/usr/sbin/mdata-put prepare-image:state running

# TODO: change to using lsb_* info
PRODUCT_FILE=/etc/product
if [[ ! -f $PRODUCT_FILE ]]; then
    fatal "Unknown Distribution...exiting"
fi
TARGET_DISTRO=`grep -w Image $PRODUCT_FILE | awk '{print $2;}'`

# Subtlety: the "Image" line in /etc/product in old ubuntu images has
# "ubuntu" (lowercase). In the new ubuntu-certified images it is "Ubuntu"
# (uppercase).
if [ $TARGET_DISTRO == "centos" ] ; then
    prepare_centos
elif [[ $TARGET_DISTRO == "ubuntu" ||
	$TARGET_DISTRO == "Ubuntu" ||
	$TARGET_DISTRO == "debian" ]] ; then
    prepare_ubuntu
fi

prepare_lib_smartdc
cleanup_logs
cleanup_disks
cleanup_ssh
cleanup_root
cleanup_metadata
cleanup_hostname

history -c
history -w || true


/usr/sbin/mdata-put prepare-image:state success
# Successful, but we still emit tail of trace log for info.
cat $TRACELOG | tail -n50 | /usr/sbin/mdata-put prepare-image:error || true
sleep 3
shutdown -h now
