#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Rsync the master in this working copy to the *production* install on
# images.joyent.com.
#

#set -x
set -e
TOP=$(cd $(dirname $0)/../; pwd)
# Using Trent's "~/.ssh/config" entry.
NODE=images

rsync -av ${TOP}/ \
    $NODE:/root/services/imgapi/ \
    --exclude "*.node" \
    --include "test/*.zfs.bz2" \
    --exclude "*.zfs.bz2" \
    --exclude .git/ \
    --exclude etc/imgapi.config.json \
    --exclude deps/ \
    --exclude doc/ \
    --exclude tools/ \
    --exclude tmp/ \
    --exclude build/

state=$(ssh ${NODE} svcs -H -o state imgapi)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm clear imgapi
else
    ssh ${NODE} svcadm restart imgapi
fi
