#!/usr/bin/env python
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

"""
Show a diff of images.joyent.com images -> datasets.joyent.com datasets.

Usage:
    img2dsdiff [<options>]

Options:
    -h, --help          Print this help and exit.
    --mirror            Push changes to datasets.joyent.com.
"""

import os
import sys
import urllib2
from pprint import pprint
import difflib
import json
import copy
from os.path import realpath, dirname
from subprocess import check_call, check_output
import logging
import shutil



#---- globals/config

log = logging.getLogger('img2dsdiff')

TOP = realpath(dirname(dirname(__file__)))
IMG_UUID_SKIPS = [
    # Because of
    #   IMAGE-484: base 13.4.0 doesn't work on SDC 6.5
    # we will exclude base/base64 13.4.0 and 13.4.1 from datasets.jo
    '2b683a82-a066-11e3-97ab-2faa44701c5a', # base  13.4.0
    '7241e29a-a07b-11e3-9a5c-53df1db058c4', # base  13.4.1
    'ff86eb8a-a069-11e3-ae0e-4f3c8983a91c', # base64  13.4.0
    'c3321aac-a07c-11e3-9430-fbb1cc12d1df'  # base64  13.4.1

    # IMGAPI-408: All existing images in images.jo at the point the
    # owner was retroactively changed to '00000000-0000-0000-0000-000000000000'
    # will be skipped, to not propagate the owner change to datasets.jo.
    'febaa412-6417-11e0-bc56-535d219f2590',
    '7456f2b0-67ac-11e0-b5ec-832e6cf079d5',
    '41da9c2e-7175-11e0-bb9f-536983f41cd8',
    '63ce06d8-7ae7-11e0-b0df-1fcf8f45c5d5',
    '184c9b38-ad3d-11e0-bad6-1b7240aaa5fc',
    '70856d1a-b860-11e0-9bbf-bf2a7494dd82',
    '7abad50e-b865-11e0-8462-730bcfdde020',
    '47e7cf16-bf5d-11e0-9c9d-77106185df1a',
    'bb6d5a10-c330-11e0-8f18-9fbfcd26660b',
    '47edd64e-c071-11e0-98c4-5bc02808198f',
    'be1d48ec-c4ca-11e0-9935-eb833f38dc43',
    '80716640-cfec-11e0-8eb8-bf491eb79cd3',
    '47e6af92-daf0-11e0-ac11-473ca1173ab0',
    'a1175b2e-db23-11e0-9cef-d7ba3111e77b',
    'f8ea0bb8-dd75-11e0-87c3-af5352ad3bd6',
    '141194fa-dd77-11e0-8539-27dd8d8264b8',
    '3fcf35d2-dd79-11e0-bdcd-b3c7ac8aeea6',
    '9199134c-dd79-11e0-8b74-1b3601ba6206',
    'aded640a-df98-11e0-b050-1f55ff3ddfa7',
    'df3589dc-df9a-11e0-a3a3-07ceee3e7d54',
    'a9380908-ea0e-11e0-aeee-4ba794c83c33',
    '8f61457a-f40a-11e0-87bd-dbd638565dbb',
    '475a1026-00a4-11e1-a2df-a71425f9c46b',
    'd91f80a6-03fe-11e1-8f84-df589c77d57b',
    '5fef6eda-05f2-11e1-90fc-13dac5e4a347',
    'aa7aeea4-0cbc-11e1-b3cb-cf1c7e291b56',
    '70ce41ae-0cbe-11e1-8c2c-3f2bb88d2a6a',
    'fcc5996a-1d34-11e1-899e-7bd98b87947a',
    'e05dbcac-1d44-11e1-b8ab-bf1bc04c2d65',
    'b4afcce4-1f8d-11e1-b4e4-fb3ae78b3768',
    '362f57e8-24d0-11e1-bbe6-e74758fd20c6',
    '39c4372c-2a50-11e1-a7fa-4bebdf5eb6e6',
    'f9a7ab78-2a5f-11e1-a2c5-2bc2fa1d27dd',
    '1796eb3a-48d3-11e1-94db-3ba91709fad9',
    '7ecb80f6-4872-11e1-badb-3f567348a4b1',
    '467ca742-4873-11e1-80ea-37290b38d2eb',
    '9dd7a770-59c7-11e1-a8f6-bfd6347ab0a7',
    '489754f2-5e01-11e1-8ff8-f770c2116b0d',
    '31bc4dbe-5e06-11e1-907c-5bed6b255fd1',
    'a963d5d0-5e29-11e1-a4d7-a31977b1e6dd',
    'f4bc70ca-5e2c-11e1-8380-fb28785857cb',
    'a54da3a0-6319-11e1-a3d9-9fdedd2f9e17',
    '8eafbcca-1f8d-11e1-b18b-036f107bbf62',
    '618d80f8-66d5-11e1-998e-e384c47940f0',
    '8c4c0f30-66df-11e1-a3f4-0f8e0a382b60',
    'f953e97e-4991-11e1-9ea4-27c6e7e8afda',
    '28445220-6eac-11e1-9ce8-5f14ed22e782',
    '76fbfd14-6eb1-11e1-9637-fb5ad39f5bfd',
    '98f38e14-6f83-11e1-bc32-2b9d0a8b6759',
    'd239389c-7535-11e1-b60a-6f75edc139df',
    '2b4466d8-7981-11e1-9be2-3b0d0e114740',
    'f4c23828-7981-11e1-912f-8b6d67c68076',
    'e4cd7b9e-4330-11e1-81cf-3bb50a972bda',
    'a93fda38-80aa-11e1-b8c1-8b1f33cd9007',
    'ce610cc2-80ac-11e1-8626-d788d6268d5b',
    'c36a3d28-80c2-11e1-9ec6-df5bd8b43f76',
    'b2845b76-80c5-11e1-9d72-5b4ca4191e12',
    '01b2c898-945f-11e1-a523-af1afbe22822',
    'f9e4be48-9466-11e1-bc41-9f993f5dff36',
    '23044e60-9511-11e1-a315-a39b02b997dc',
    'beabff26-b405-11e1-8281-4fd3c943ceb5',
    'c952c558-b640-11e1-b30c-0376247e919c',
    '399e09fc-c448-11e1-b3c8-a3d517dfbb07',
    '8418dccc-c9c6-11e1-91f4-5fb387d839c5',
    'd0eebb8e-c9cb-11e1-8762-2f01c4acd80d',
    'b3703b1e-af59-11e1-bad3-2f2c3c9d0aa1',
    'bbab652a-af5d-11e1-bb80-23b0b09d0df9',
    'e16639f2-cc95-11e1-9026-c339822d3c0f',
    '9551fdbc-cc9a-11e1-a9e7-eb1e788a8690',
    '3766d58c-d777-11e1-89c1-4fa1b8ed5c1e',
    '8da4bc54-d77f-11e1-8f6f-cfe8e7177a23',
    '93ae1e02-da76-11e1-9e01-a3e8dd3b47e0',
    '45e0fa58-db5e-11e1-a1f0-df041127b335',
    '9012a9c2-f15d-11e1-a33a-afaec53ebde9',
    'e8c41d40-f161-11e1-b839-a3631c115653',
    '2baee822-f1eb-11e1-8383-f762d43a424c',
    '15c77de2-f1ed-11e1-8688-47d8455c7932',
    '9604da58-f1ee-11e1-aba1-dbda3337ec46',
    '3390ca7c-f2e7-11e1-8818-c36e0b12e58b',
    'a0f8cf30-f2ea-11e1-8a51-5793736be67c',
    '6bf31ce2-f384-11e1-a338-e39c2fe4ab59',
    'dc1a8b5e-043c-11e2-9d94-0f3fcb2b0c6d',
    '60a3b1fa-0674-11e2-abf5-cb82934a8e24',
    '55330ab4-066f-11e2-bd0f-434f2462fada',
    '8700b668-0da4-11e2-bde4-17221283a2f4',
    '1fc068b0-13b0-11e2-9f4e-2f3f6a96d9bc',
    'b00acc20-14ab-11e2-85ae-4f03a066e93e',
    '2539f6de-0b5a-11e2-b647-fb08c3503fb2',
    'e6ac6784-44b3-11e1-8555-87c3dd87aafe',
    '3f8a3d02-43e4-11e1-9565-7f82a075e289',
    '71101322-43a5-11e1-8f01-cf2a3031a7f4',
    'ef22b182-3d7a-11e2-a7a9-af27913943e2',
    'aa583f78-3d83-11e2-9188-fff9b605718d',
    '84cb7edc-3f22-11e2-8a2a-3f2a7b148699',
    'fdea06b0-3f24-11e2-ac50-0b645575ce9d',
    'fb6ef720-55c1-11e2-b6de-bf6869fd8d41',
    '6344c3f4-64d9-11e2-af3d-af797e5b19ca',
    '1327ed36-5130-11e2-95a8-9b5a153adf3e',
    '46ecf60e-52c8-11e2-b212-9b51fc749547',
    '1d4fd806-6ef8-11e2-93ab-4f22d6d207c9',
    'd2fc0a96-61d1-11e2-8701-c7c137935369',
    '4bf9530a-7ae5-11e2-bb4e-3bad5fbc3de9',
    '03d515f2-872c-11e2-8314-8387b5044570',
    'bad2face-8738-11e2-ac72-0378d02f84de',
    '3162a91e-8b5d-11e2-a78f-9780813f9142',
    '60ed3a3e-92c7-11e2-ba4a-9b6d5feaa0c4',
    'cf7e2f40-9276-11e2-af9a-0bad2233fb0b',
    'e1896142-a382-11e2-bf8b-0719c824c61e',
    'e6f10814-a38d-11e2-8138-67b96e228c1e',
    'da144ada-a558-11e2-8762-538b60994628',
    '014e2254-a853-11e2-81c9-b318c31fa17a',
    '87c556ac-ab9d-11e2-914d-07682fcab47d',
    'f669428c-a939-11e2-a485-b790efc0f0c1',
    '9eac5c0c-a941-11e2-a7dc-57a6b041988f',
    '3882b5da-b0e8-11e2-b3a9-dbcf26c3e051',
    'beb2dbd4-b26f-11e2-8ad4-935c80092aa6',
    '1567edb0-b33e-11e2-a0d2-bf73e2825ffe',
    '94384a12-bbeb-11e2-aec2-2bfa9742484b',
    'd2ba0f30-bbe8-11e2-a9a2-6bc116856d85',
    '30e9e4c8-bbf2-11e2-ac3b-3b598ee13393',
    'e42f8c84-bbea-11e2-b920-078fab2aab1f',
    'df8d2ee6-d87f-11e2-b257-2f02c6f6ce80',
    'bae3f528-e01f-11e2-b2cb-1360087a7d5f',
    '274bc2bc-d919-11e2-b797-83245409fbeb',
    '48489174-e351-11e2-88c0-a31eb2b342ee',
    'e3364212-05c0-11e3-9576-3f3ee9e951a7',
    '0084dad6-05c1-11e3-9476-8f8320925eea',
    '399775e4-163e-11e3-8d42-7b14b732ae17',
    'ec5defa8-16fe-11e3-948e-8f59b3488902',
    '34509f68-1ae7-11e3-b816-d3edf71c7840',
    '4b4c141e-1fb4-11e3-a10e-6f99cfdf8806',
    'b83f8276-1fdd-11e3-989b-4bddb088a8a0',
    '17c98640-1fdb-11e3-bf51-3708ce78e75a',
    'b779b49a-29e4-11e3-9b1d-0b0b41ccdcad',
    'd2409672-29f3-11e3-ba86-6f782523cb41',
    'dac2ad6e-2aa5-11e3-885f-8fd408fc6a82',
    '325dbc5e-2b90-11e3-8a3e-bfdcb1582a8d',
    'ffed3d9e-2c2f-11e3-9a12-bf5267821b0b',
    '133263be-3c2c-11e3-8d3a-a30c43ae58fd',
    '610e04c4-3cc4-11e3-9867-df64b21b66fe',
    '56a0655c-3cc6-11e3-9c79-5701599fdf05',
    'a1d74530-4212-11e3-8a71-a7247697c8f2',
    '7fa676e2-4709-11e3-916d-83ffcd857200',
    '753ceee6-5372-11e3-8f4e-f79c1154e596',
    '87b9f4ac-5385-11e3-a304-fb868b82fe10',
    '4aec529c-55f9-11e3-868e-a37707fcbe86',
    '75ec04ce-55fe-11e3-9252-afb57e4da368',
    'fb6e7820-60ee-11e3-93b6-7f34ea3f2616',
    'dee73ee2-69ab-11e3-b593-a3f1f80ef403',
    'c353c568-69ad-11e3-a248-db288786ea63',
    '81223438-7874-11e3-9edf-8f1e15269924',
    '40d56fc2-788c-11e3-8e0e-ab90eb060ee7',
    '74c3b232-7961-11e3-a7a7-935768270b93',
    'c56ed646-82d8-11e3-849e-eb2c0535bf06',
    '649e0c72-89ec-11e3-a7c2-97e6a67823b0',
    'df81f45e-8f9f-11e3-a819-93fab527c81e',
    '2b683a82-a066-11e3-97ab-2faa44701c5a',
    'ff86eb8a-a069-11e3-ae0e-4f3c8983a91c',
    '7241e29a-a07b-11e3-9a5c-53df1db058c4',
    'c3321aac-a07c-11e3-9430-fbb1cc12d1df',
    '835e27b2-a47e-11e3-9eb6-e78ef6d1ee8f',
    '1a4bdf60-b8da-11e3-a334-0f09e71eb510',
    '7c384e62-b8de-11e3-885f-9bb74b4e394b',
    '78904c3a-ba8a-11e3-8d2c-e73f8ba0674a',
    '398deede-c025-11e3-8b24-f3ba141900bd',
    'effeb440-c026-11e3-b235-afe25a8d326b',
    '0fbd0a74-c028-11e3-ac6a-bf348e9f760c',
    'edd43ca8-c0ee-11e3-a027-c3a9f2cd2f6a',
    '19daa264-c4c4-11e3-bec3-c30e2c0d4ec0',
    'd763e880-c669-11e3-b742-0f142d68b997',
    '19edf83a-c674-11e3-af63-a78d671948c1',
    'dc0688b2-c677-11e3-90ac-13373101c543',
    '9ab3f722-d136-11e3-9f3a-6fcb23726ee3',
    'caac17a4-d512-11e3-9d41-b756aebcb18f',
    '8639203c-d515-11e3-9571-5bf3a74f354f',
    'a2969206-d604-11e3-be79-dfd0c3676b44',
    '5ba3a060-dab8-11e3-94ff-4bdb68a7bd2a',
    '9c1033b8-dabb-11e3-8d26-63cbb658ef40',
    '6d5debc0-dac3-11e3-8bc0-dfc25b68fd97',
    'd05983cc-db7e-11e3-97fc-539ccfe9fa95',
    '45ad5854-db8b-11e3-8f4c-0bc011b22b7d',
    'e65e0c4c-dc4b-11e3-b843-93672a0b57d8',
    'bb41287c-e02a-11e3-aa6b-db678b82f5fc',
    '4b348706-e122-11e3-9cb4-9b2c5062255c',
    '1daa8e14-e1ba-11e3-bd59-a3971b58fa36',
    '4b46e5e4-f17c-11e3-9da1-17ebb4120b97',
    '39a95440-f193-11e3-9ce4-332a0d637d3a',

]
IMG_NAME_SKIPS = [
    # sngl images are only for images.joyent.com. Only works on recent
    # (post-6.5) platforms so don't want it exposed on datasets.jo.
    'sngl'
]



#---- errors

class Error(Exception):
    pass


#---- internal support stuff

def _getUrl(url):
    f = urllib2.urlopen(url)
    try:
        content = f.read()
    finally:
        f.close()
    return content

def _getJsonUrl(url):
    content = _getUrl(url)
    return json.loads(content)

all_file_paths = set()  # track all these to error on duplicates
def downgrade_image_inplace(img):
    drop = ["v", "homepage", "tags", "billing_tags"]
    for field in drop:
        if img.has_key(field):
            del img[field]

    if img["state"] != "active":
        raise ValueError("image %(uuid)s is not active: state=%(state)r" % img)
    del img["state"]

    assert not img["disabled"]
    del img["disabled"]

    assert img["public"]
    del img["public"]

    # owner fields
    img["creator_uuid"] = img["vendor_uuid"] = img["owner"]
    del img["owner"]

    img["platform_type"] = "smartos"

    if img["published_at"].endswith(':00Z'):
        img["published_at"] = img["published_at"][:-4] + 'Z'
    img["updated_at"] = img["published_at"]
    img["created_at"] = img["published_at"]

    if img.has_key("urn"):
        urn = img["urn"].split(':')
        img["cloud_name"] = urn[0]
        img["creator_name"] = urn[1]

    if img.has_key("image_size"):
        img["image_size"] = str(img["image_size"])

    if img.has_key("acl") and len(img["acl"]) == 0:
        del img["acl"]

    # Specific manual hacks for some UUIDs on datasets.jo.
    uuid = img["uuid"]

    # files
    f = img["files"][0]
    ext = {"bzip2": ".bz2", "gzip": ".gz", "none": ""}[f["compression"]]
    if uuid in (
            "da144ada-a558-11e2-8762-538b60994628",
            "d2ba0f30-bbe8-11e2-a9a2-6bc116856d85",
            "94384a12-bbeb-11e2-aec2-2bfa9742484b",
            "87c556ac-ab9d-11e2-914d-07682fcab47d",
            "3162a91e-8b5d-11e2-a78f-9780813f9142",
            "1327ed36-5130-11e2-95a8-9b5a153adf3e",
            "014e2254-a853-11e2-81c9-b318c31fa17a",
        ):
        f["path"] = "%s-%s.zfs%s" % (img["name"], img["version"], ext)
    elif uuid == "30e9e4c8-bbf2-11e2-ac3b-3b598ee13393":
        f["path"] = "%s.4-%s.zfs%s" % (img["name"], img["version"], ext)
    elif uuid == "e42f8c84-bbea-11e2-b920-078fab2aab1f":
        f["path"] = "%s-18-%s.zfs%s" % (img["name"], img["version"], ext)
    elif uuid == "46ecf60e-52c8-11e2-b212-9b51fc749547":
        f["path"] = "%s-%s-1.zfs%s" % (img["name"], img["version"], ext)
    elif uuid in (
            "e4cd7b9e-4330-11e1-81cf-3bb50a972bda",
            "71101322-43a5-11e1-8f01-cf2a3031a7f4",
        ):
        f["path"] = "%s-1.0.0.zvol%s" % (img["name"], ext)
    elif img["type"] == "zvol":
        f["path"] = "%s-%s.zvol%s" % (img["name"], img["version"], ext)
    else:
        f["path"] = "%s-%s.zfs%s" % (img["name"], img["version"], ext)
    if f["path"] in all_file_paths:
        raise ValueError("duplicate file 'path': %r" % f["path"])
    all_file_paths.add(f["path"])
    f["url"] = "https://datasets.joyent.com/datasets/%s/%s" % (img["uuid"], f["path"])
    del f["compression"]





#---- main functionality

def img2dsdiff():
    if False:
        datasets = json.load(open('/var/tmp/datasets.json'))
        images = json.load(open('/var/tmp/images.json'))
    else:
        datasets = _getJsonUrl('https://datasets.joyent.com/datasets')
        #open('/var/tmp/datasets.json', 'w').write(json.dumps(datasets))
        images = _getJsonUrl('https://images.joyent.com/images')
        #open('/var/tmp/images.json', 'w').write(json.dumps(images))

    # Key by uuid
    datasets = dict((d['uuid'], d) for d in datasets)
    images = dict((i['uuid'], i) for i in images)

    # Find all the diffs in UUID order.
    ds_uuids = set(datasets.keys())
    img_uuids = set(images.keys())
    all_uuids = ds_uuids.union(img_uuids)
    #pprint(uuids)

    diffs = []
    for uuid in sorted(all_uuids):
        #print "--", uuid
        if uuid in ds_uuids and uuid not in img_uuids:
            diffs.append({
                "uuid": uuid,
                "action": "delete",
                "msg": "Only in datasets.joyent.com: image %s (%s %s)" % (
                    uuid, datasets[uuid]["name"], datasets[uuid]["version"])
            })
        elif uuid not in ds_uuids and uuid in img_uuids:
            if (uuid not in IMG_UUID_SKIPS
                    and images[uuid]["name"] not in IMG_NAME_SKIPS):
                diffs.append({
                    "uuid": uuid,
                    "action": "add",
                    "image": images[uuid],
                    "msg": "Only in images.joyent.com: image %s (%s %s)" % (
                        uuid, images[uuid]["name"], images[uuid]["version"])
                })
        else:
            #print "--", uuid

            i = copy.deepcopy(images[uuid])
            downgrade_image_inplace(i)

            # Note: Don't compare ownership, that's all messed up btwn
            # 'admin' or 'all zeros' in images.jo vs 'sdc' user uuid in
            # datasets.jo.
            d = copy.deepcopy(datasets[uuid])
            del d["creator_uuid"]
            del d["vendor_uuid"]
            del i["creator_uuid"]
            del i["vendor_uuid"]

            # Comparing times for images mirrored from images.jo
            # to dataset.jo is a fools errand, because datasets.jo
            # import overrides those values.
            for field in ["created_at", "published_at", "updated_at"]:
                del d[field]
                del i[field]

            d_str = json.dumps(d, indent=2, sort_keys=True)
            downgraded_i_str = json.dumps(i, indent=2, sort_keys=True)
            diff = list(difflib.unified_diff(
                downgraded_i_str.splitlines(True),
                d_str.splitlines(True),
                'https://images.joyent.com/images/' + uuid,
                'https://datasets.joyent.com/datasets/' + uuid,
                ))
            #pprint(diff)
            diff_str = ''.join(diff)
            if diff_str:
                diffs.append({
                    "uuid": uuid,
                    "action": "diff",
                    "msg": diff_str
                })
    return diffs

def _indent(s, indent='    '):
    return indent + indent.join(s.splitlines(True))

def run(argv):
    from subprocess import check_call
    print ' '.join(argv)
    check_call(argv, shell=True)

def add_image(image):
    CONFIG = json.loads(open('/root/config/img2dsdiff.config.json').read())

    dataset = copy.deepcopy(image)
    downgrade_image_inplace(dataset)
    uuid = dataset["uuid"]

    # Force ownership to 'sdc' user.
    # We are forcing the ownership/creator_uuid to the 'sdc'
    # user (uuid 352971aa-31ba-496c-9ade-a379feaecd52) because
    # DSAPI gets picky if you don't match that and the 'sdc'
    # creator_name (from the urn). We *could* support 'jpc' if we
    # need to, but really those shouldn't go on datasets.jo.
    assert dataset["creator_name"] == "sdc", "We only want 'sdc' as the creator_name here, not '%s'" % dataset["creator_name"]
    dataset["creator_uuid"] = dataset["vendor_uuid"] = '352971aa-31ba-496c-9ade-a379feaecd52'

    tmpd = '/var/tmp/img2dsdiff.%s.%s' % (os.getpid(), uuid)
    os.makedirs(tmpd)

    print "Image manifest on images.jo:"
    print _indent(json.dumps(image, indent=2, sort_keys=True))

    print "Dataset manifest downgraded for datasets.jo:"
    dataset_str = json.dumps(dataset, indent=2, sort_keys=True)
    print _indent(dataset_str)
    open(os.path.join(tmpd, 'dsmanifest'), 'w').write(dataset_str)

    print "Download the image file"
    check_call([
        '/opt/local/bin/curl', '-kOsS', 'http://localhost:8080/images/%s/file' % uuid,
    ], cwd=tmpd)

    print "Push to datasets.joyent.com"
    print check_output([
        '/opt/local/bin/curl', '-sSi',
        # Note: presuming no url encoding of user/pass necessary here.
        'https://%s:%s@datasets.joyent.com/datasets/%s' % (
            CONFIG["dsapi_user"], CONFIG["dsapi_password"], uuid),
        '-X', 'PUT',
        '-F', 'manifest=@dsmanifest',
        '-F', '%s=@file' % dataset["files"][0]["path"]
    ], cwd=tmpd)

    shutil.rmtree(tmpd)



#---- mainline

def main(argv):
    if '-h' in argv or '--help' in argv:
        sys.stdout.write(__doc__)
        return
    diffs = img2dsdiff()
    if '--mirror' in argv:
        for diff in diffs:
            uuid = diff["uuid"]
            action = diff["action"]
            if action == "add":
                print "Add image %s to datasets.joyent.com" % uuid
                add_image(diff["image"])
            elif action == "delete":
                print "*Skipping* delete of image %s from datasets.joyent.com" % uuid
            elif action == "diff":
                print "Image %s differs on datasets.joyent.com (what to do?)" % uuid
                print diff["msg"]
    else:
        for diff in diffs:
            print diff["msg"]


## {{{ http://code.activestate.com/recipes/577258/ (r5+)
if __name__ == "__main__":
    try:
        retval = main(sys.argv)
    except KeyboardInterrupt:
        sys.exit(1)
    except SystemExit:
        raise
    except:
        import traceback, logging
        if not log.handlers and not logging.root.handlers:
            logging.basicConfig()
        skip_it = False
        exc_info = sys.exc_info()
        if hasattr(exc_info[0], "__name__"):
            exc_class, exc, tb = exc_info
            if isinstance(exc, IOError) and exc.args[0] == 32:
                # Skip 'IOError: [Errno 32] Broken pipe': often a cancelling of `less`.
                skip_it = True
            if not skip_it:
                tb_path, tb_lineno, tb_func = traceback.extract_tb(tb)[-1][:3]
                log.error("%s (%s:%s in %s)", exc_info[1], tb_path,
                    tb_lineno, tb_func)
        else:  # string exception
            log.error(exc_info[0])
        if not skip_it:
            if log.isEnabledFor(logging.DEBUG):
                traceback.print_exception(*exc_info)
            sys.exit(1)
    else:
        sys.exit(retval)
## end of http://code.activestate.com/recipes/577258/ }}}

