#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# Login to imgapi on kvm7 and run the test suite.
#

#set -x
set -o errexit
set -o pipefail

NODE=root@10.2.207.2

ssh -T $NODE "/opt/smartdc/bin/sdc-login imgapi 'cd /opt/smartdc/imgapi && ./test/runtests $@'"
