#!/bin/bash
#
# Login to imgapi on kvm7 and run the test suite.
#

#set -x
set -o errexit
set -o pipefail

NODE=root@10.2.207.2

ssh -T $NODE "/opt/smartdc/bin/sdc-login imgapi 'cd /opt/smartdc/imgapi && ./test/runtests $@'"
